### PR TITLE
Refactor get_video_name allowing dot(.) on filenames

### PR DESCRIPTION
**Pull request by leocaseiro**
Using `pathinfo` is much safer than `strrpos`. 

Also if the user would like to name its file with dots, such as `01_01.category.filename.mp4`, it'll work from now on.

### CODE REVIEW

**Comment by bobbywalters** [comment]
Thanks for reviewing the code and providing suggestions.

**get_video_name**
- The implementation using strrpos had identical output as pathinfo with unit tests I ran. Periods in the name weren't a problem.
- Post names will never be saved with a period in them anyway because `sanitize_title` will strip them out when a post is inserted or updated. Also remember post_title (generally for display purposes) is not the same as post_name (usually URLs, unique identifier, slug).
- However, this did get me thinking if the URL had a query parameter it would not return the proper video name. This may never happen but perhaps another plugin was adding an OAuth token to all URLs or someone was misbehaving. So I ended up using `parse_url` and your suggestion of `pathinfo` to be on the safe side.
- Some light performance testing on PHP 7.0.9 shows the updated `WebVTT::get_video_name` is bit a faster.

**sanitize_title**
- After reviewing the [WP_Query class](https://core.trac.wordpress.org/browser/tags/4.6/src/wp-includes/query.php#L2717) it looks like `sanitize_title_for_query` is more appropriate.
- To be a little more cautious I opted to put the `sanitize_title_for_query` call in `WebVTT::posts_where` just in case someone manipulated a query object on their own.

Thanks again for the feedback. These were good thought provoking finds.

**Comment by leocaseiro** [comment]
Hi @bobbywalters, thanks for refactoring and give me an awesome feedback with theory and so on.

Yeah! Most of my files are exported with dots such as (01.Example.name-of-the-file.mp4) and I was having issues to read the subtitles because of the ".";

I didn't know you had unit tests, that would be nice pushing them here, so I could've run.

Your solution is better than my suggestion. Thanks anyway.

PS: Later I hope getting some more time to work on the playlist. It wasn't easy when tried.

**Comment by bobbywalters** [comment]
I have been working on the playlist and will have that ready soon. Been thinking on a couple ideas to see what would be a better implementation.

**Comment by leocaseiro** [comment]
@bobbywalters, you are a legend!!! 😄

**Pull request closed without merging**
